name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@variocube'
      - run: npm ci
        working-directory: ./lib
      - run: npm run build
        working-directory: ./lib
      - if: startsWith(github.ref, 'refs/tags/')
        run: npm publish
        working-directory: ./lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}